# Generated by Django 4.0.1 on 2022-05-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('indicator', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=400)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
