# Generated by Django 4.0.1 on 2022-05-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0004_remove_indicators_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
