# Generated by Django 4.0.1 on 2022-06-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0010_remove_companyinstance_company_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='indicator_values',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
