# Generated by Django 4.0.1 on 2022-06-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0012_alter_companyinstance_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinstance',
            name='recording_date',
        ),
    ]
