# Generated by Django 4.0.1 on 2022-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_app', '0013_remove_companyinstance_recording_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_info',
        ),
        migrations.AlterField(
            model_name='indicators',
            name='indicator',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='indicator_values',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
